//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using System.Collections.Generic;
    
    public partial class Krava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Krava()
        {
            this.ProizvodnjaMlijeka = new HashSet<ProizvodnjaMlijeka>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public Nullable<int> PasminaId { get; set; }
        public string VeterinarskiBroj { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public int BrojTeladi { get; set; }
        public System.DateTime DatumDolaska { get; set; }
    
        public virtual Pasmina Pasmina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProizvodnjaMlijeka> ProizvodnjaMlijeka { get; set; }

        public override string ToString()
        {
            return Ime;
        }
    }
}
