//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProizvodnjaMlijeka
    {
        public int Id { get; set; }
        public Nullable<int> KravaId { get; set; }
        public System.DateTime DatumUzimanja { get; set; }
        public double Kolicina { get; set; }
        public double PostotakMasnoce { get; set; }
        public double PostotakMikroOrg { get; set; }
    
        public virtual Krava Krava { get; set; }
    }
}
